#!/usr/bin/env bash
# Script that configures Nginx with a custom HTTP response header

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Define the custom header name
custom_header_name="X-Served-By"

# Define the custom header value (hostname of the server)
custom_header_value=$(hostname)

# Configure Nginx to add the custom header
sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header $custom_header_name $custom_header_value;

    location / {
        proxy_pass http://localhost:5000; # Adjust the proxy_pass accordingly
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOL

# Restart Nginx to apply changes
sudo service nginx restart
