#!/usr/bin/env bash
# Script that installs and configures HAproxy on lb-01 server

# Update package list and install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAproxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg" <<EOL
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Make HAproxy manageable via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy to apply changes
sudo service haproxy restart

