#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
CONFIG="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 240202-web-01 3.80.18.189:80 check
   server 240202-web-02 18.209.224.4:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
# Backup original config file before attempt modifications

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Overwrite the configuration file with the new configuration
printf "%s" "$CONFIG" | sudo tee /etc/haproxy/haproxy.cfg

# Output information about the configured web servers
echo "Configured web servers: web-01, web-02"

# Restart HAProxy to apply changes
sudo service haproxy restart
